
name = "BrushableHeatmap"
uuid = "1b08a953-4be3-4667-9a23-286608afee68"
authors = ["Marina Evers <marina.evers@uni-muenster.de>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
